name: conditional-workflow

on:
    workflow_dispatch:
        inputs:
            simulate_failure:
                description: "Simulate failure in the workflow"
                type: boolean
                required: false
                default: false
            target_branch:
                description: "Target branch for the workflow"
                type: string
                required: true
                default: main

    push:
        branches:
            - main
            - develop
jobs:
    conditional-demo:
        name: Conditional-steps
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Always run
              run:  echo " This step always runs"
            
            - name: Conditional Step run only on main branch
              if: github.ref == 'ref/heads/main'
              run: echo " This step runs  only on the   main branch"

            - name: Only run on non-main branch
              if: github.ref != 'ref/heads/main'
              run: echo " This step runs  only on the   non-main branch" 

            - name: Run only on push event
              if: github.event_name == 'push'
              run: echo " This step runs  only on the   push events"  
              
            - name: Run only on workflow_dispatch event
              if: github.event_name == 'workflow_dispatch'
              run:  |
                echo "This step runs  only on the   workflow dispatch events" 
                echo " The input value for simulate_failure is: ${{ github.event.inputs.simulate_failure }}"
                echo " The input value for target_branch is: ${{ github.event.inputs.target_branch }}"
                echo " Manually triggered workflow : ${{ github.actor }}"


    



